apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: clusterexternalsecret
spec:
  namespaces:
    - kafka
    - prometheus
  externalSecretSpec:
    refreshInterval: "0"
    secretStoreRef:
      name: clustersecretstore
      kind: ClusterSecretStore
    target:
      name: kafka-brokers
      creationPolicy: Owner
    data:
    - secretKey: brokers
      remoteRef:
        key: kafka/brokers
        property: brokers
    - secretKey: broker_1
      remoteRef:
        key: kafka/brokers
        property: broker_1
    - secretKey: broker_2
      remoteRef:
        key: kafka/brokers
        property: broker_2
    - secretKey: broker_3
      remoteRef:
        key: kafka/brokers
        property: broker_3
    - secretKey: prometheus-scrape-config.yaml
      remoteRef:
        key: kafka/brokers
        property: prometheus_config
