{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "broker_id",
    "label": "Broker Id",
    "query": "label_values(kafka_server_KafkaServer_Value, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Healthcheck",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"kafka\",instance=~\"$broker_id\",name=\"ActiveControllerCount\"})"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_ReplicaManager_Value{job=\"kafka\",instance=~\"$broker_id\",name=\"LeaderCount\"})"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "stat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_ControllerStats_Count{job=\"kafka\",instance=~\"$broker_id\",name=\"UncleanLeaderElectionsPerSec\"})"
    }
   ]
  },
  {
   "title": "Preferred Replica Imbalance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"kafka\",instance=~\"$broker_id\",name=\"PreferredReplicaImbalanceCount\"})"
    }
   ]
  },
  {
   "title": "Broker network throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_MeanRate{job=\"kafka\",instance=~\"$broker_id\",topic!=\"\",name=\"BytesInPerSec\"}[5m]))",
     "legendFormat": "Bytes in"
    },
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_MeanRate{job=\"kafka\",instance=~\"$broker_id\",topic!=\"\",name=\"BytesOutPerSec\"}[5m]))",
     "legendFormat": "Bytes out"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"kafka\",instance=~\"$broker_id\",name=\"OfflinePartitionsCount\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{job=\"kafka\",instance=~\"$broker_id\",name=\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "stat",
   "description": "Number of partitions under min insync replicas.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_Partition_Value{job=\"kafka\",instance=~\"$broker_id\",name=\"UnderMinIsr\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{job=\"kafka\",instance=~\"$broker_id\",name=\"PartitionCount\"})"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\",instance=~\"$broker_id\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(java_lang_Memory_HeapMemoryUsage_used{job=\"kafka\",instance=~\"$broker_id\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\",instance=~\"$broker_id\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Throughput In/Out",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "iops", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",topic!=\"\",name=\"MessagesInPerSec\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",topic!=\"\",name=\"BytesInPerSec\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",topic!=\"\",name=\"BytesOutPerSec\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "iops", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",topic!=\"\",name=\"MessagesInPerSec\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",topic!=\"\",name=\"BytesInPerSec\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",topic!=\"\",name=\"BytesOutPerSec\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thread utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Processor Avg Idle Percent",
     "type": "graph",
     "description": "Average fraction of time the network processor threads are idle. Values are between 0 (all resources are used) and 100 (all resources are available)\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_network_SocketServer_Value{job=\"kafka\",instance=~\"$broker_id\",name=\"NetworkProcessorAvgIdlePercent\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Request Handler Avg Idle Percent",
     "type": "graph",
     "description": "Average fraction of time the request handler threads are idle. Values are between 0 (all resources are used) and 100 (all resources are available).\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_server_KafkaRequestHandlerPool_MeanRate{job=\"kafka\",instance=~\"$broker_id\",name=\"RequestHandlerAvgIdlePercent\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Zookeeper Request Latency",
     "type": "graph",
     "description": "Latency in millseconds for ZooKeeper requests from broker.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_server_ZooKeeperClientMetrics_Mean{job=\"kafka\",instance=~\"$broker_id\",name=\"ZooKeeperRequestLatencyMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Zookeeper connections per sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_SessionExpireListener_Count{job=\"kafka\",instance=~\"$broker_id\",name=\"ZooKeeperSyncConnectsPerSec\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Zookeeper expired connections per sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_SessionExpireListener_Count{job=\"kafka\",instance=~\"$broker_id\",name=\"ZooKeeperExpiresPerSec\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Zookeeper disconnect per sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_SessionExpireListener_Count{job=\"kafka\",instance=~\"$broker_id\",name=\"ZooKeeperDisconnectsPerSec\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Zookeeper auth failures per sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_SessionExpireListener_Count{job=\"kafka\",instance=~\"$broker_id\",name=\"ZooKeeperAuthFailuresPerSec\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Isr Shrinks / Expands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IsrShrinks per Sec",
     "type": "graph",
     "description": ": The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leader’s offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_ReplicaManager_Count{job=\"kafka\",instance=~\"$broker_id\",name=\"IsrShrinksPerSec\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IsrExpands per Sec",
     "type": "graph",
     "description": ": The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leader’s offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_ReplicaManager_Count{job=\"kafka\",instance=~\"$broker_id\",name=\"IsrExpandsPerSec\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Log size per Topic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_log_Log_Value{job=\"kafka\",instance=~\"$broker_id\",name=\"Size\"}) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Log size per Broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_log_Log_Value{job=\"kafka\",instance=~\"$broker_id\",name=\"Size\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Producer Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Producer - RequestQueueTimeMs",
     "type": "graph",
     "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isn’t large enough. The request queue size should match the number of connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"Produce\",name=\"RequestQueueTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Producer - LocalTimeMs",
     "type": "graph",
     "description": "In most cases, a high value can imply slow local storage or the storage is a bottleneck. One should also investigate LogFlushRateAndTimeMs to know how long page flushes are taking, which will also indicate a slow disk. In the case of FetchFollower requests, time spent in LocalTimeMs can be the result of a ZooKeeper write to change the ISR.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"Produce\",name=\"LocalTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Producer - RemoteTimeMs",
     "type": "graph",
     "description": "A high value can imply a slow network connection. For fetch request, if the remote time is high, it could be that there is not enough data to give in a fetch response. This can happen when the consumer or replica is caught up and there is no new incoming data. If this is the case, remote time will be close to the max wait time, which is normal. Max wait time is configured via replica.fetch.wait.max.ms and fetch.max.wait.ms.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"Produce\",name=\"RemoteTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Producer - ResponseQueueTimeMs",
     "type": "graph",
     "description": "A high value can imply there aren't enough network threads or the network can’t dequeue responses quickly enough, causing back pressure in the response queue.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"Produce\",name=\"ResponseQueueTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Producer - ResponseSendTimeMs",
     "type": "graph",
     "description": "A high value can imply the zero-copy from disk to the network is slow, or the network is the bottleneck because the network can’t dequeue responses of the TCP socket as quickly as they’re being created. If the network buffer gets full, Kafka will block.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"Produce\",name=\"ResponseSendTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Consumer - RequestQueueTimeMs",
     "type": "graph",
     "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isn’t large enough. The request queue size should match the number of connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"Fetch\",name=\"RequestQueueTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Consumer - LocalTimeMs",
     "type": "graph",
     "description": "In most cases, a high value can imply slow local storage or the storage is a bottleneck. One should also investigate LogFlushRateAndTimeMs to know how long page flushes are taking, which will also indicate a slow disk. In the case of FetchFollower requests, time spent in LocalTimeMs can be the result of a ZooKeeper write to change the ISR.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"Fetch\",name=\"LocalTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Consumer - RemoteTimeMs",
     "type": "graph",
     "description": "A high value can imply a slow network connection. For fetch request, if the remote time is high, it could be that there is not enough data to give in a fetch response. This can happen when the consumer or replica is caught up and there is no new incoming data. If this is the case, remote time will be close to the max wait time, which is normal. Max wait time is configured via replica.fetch.wait.max.ms and fetch.max.wait.ms.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"Fetch\",name=\"RemoteTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Consumer - ResponseQueueTimeMs",
     "type": "graph",
     "description": "A high value can imply there aren't enough network threads or the network can’t dequeue responses quickly enough, causing back pressure in the response queue.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"Fetch\",name=\"ResponseQueueTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Consumer - ResponseSendTimeMs",
     "type": "graph",
     "description": "A high value can imply the zero-copy from disk to the network is slow, or the network is the bottleneck because the network can’t dequeue responses of the TCP socket as quickly as they’re being created. If the network buffer gets full, Kafka will block.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"Fetch\",name=\"ResponseSendTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fetch Follower Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "FetchFollower - RequestQueueTimeMs",
     "type": "graph",
     "description": "A high value can imply there aren't enough IO threads or the CPU is a bottleneck, or the request queue isn’t large enough. The request queue size should match the number of connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"FetchFollower\",name=\"RequestQueueTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FetchFollower - LocalTimeMs",
     "type": "graph",
     "description": "In most cases, a high value can imply slow local storage or the storage is a bottleneck. One should also investigate LogFlushRateAndTimeMs to know how long page flushes are taking, which will also indicate a slow disk. In the case of FetchFollower requests, time spent in LocalTimeMs can be the result of a ZooKeeper write to change the ISR.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"FetchFollower\",name=\"LocalTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FetchFollower - RemoteTimeMs",
     "type": "graph",
     "description": "A high value can imply a slow network connection. For fetch request, if the remote time is high, it could be that there is not enough data to give in a fetch response. This can happen when the consumer or replica is caught up and there is no new incoming data. If this is the case, remote time will be close to the max wait time, which is normal. Max wait time is configured via replica.fetch.wait.max.ms and fetch.max.wait.ms.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"FetchFollower\",name=\"RemoteTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FetchFollower - ResponseQueueTimeMs",
     "type": "graph",
     "description": "A high value can imply there aren't enough network threads or the network can’t dequeue responses quickly enough, causing back pressure in the response queue.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"FetchFollower\",name=\"ResponseQueueTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FetchFollower - ResponseSendTimeMs",
     "type": "graph",
     "description": "A high value can imply the zero-copy from disk to the network is slow, or the network is the bottleneck because the network can’t dequeue responses of the TCP socket as quickly as they’re being created. If the network buffer gets full, Kafka will block.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"FetchFollower\",name=\"ResponseSendTimeMs\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Produce Request Per Sec",
     "type": "stat",
     "description": "Produce request rate.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",name=\"RequestsPerSec\"}[1m]))"
      }
     ]
    },
    {
     "title": "Fetch Request Per Sec",
     "type": "stat",
     "description": "Fetch request rate.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"FetchConsumer\",name=\"RequestsPerSec\"}[1m]))"
      }
     ]
    },
    {
     "title": "Metadata Request Per Sec",
     "type": "stat",
     "description": "Metadata request rate.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"Metadata\",name=\"RequestsPerSec\"}[1m]))"
      }
     ]
    },
    {
     "title": "Offset Commit Request Per Sec",
     "type": "stat",
     "description": "Offset Commit request rate.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_RequestMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",request=\"OffsetCommit\",name=\"RequestsPerSec\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Message Conversion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of procuded message conversion",
     "type": "graph",
     "description": "The number of messages produced converted to match the log.message.format.version.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_BrokerTopicMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",name=\"ProduceMessageConversionsPerSec\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Number of consumed message conversion",
     "type": "graph",
     "description": "The number of messages consumed converted at consumer to match the log.message.format.version.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_BrokerTopicMetrics_Count{job=\"kafka\",instance=~\"$broker_id\",name=\"FetchMessageConversionPerSec\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  }
 ]
}